name:                leadbeater
version:             0.1.0.0
github:              "wenkokke/leadbeater"
license-file:        LICENSE
author:              "Wen Kokke"
maintainer:          "wen.kokke@ed.ac.uk"
copyright:           "2019 Wen Kokke"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/leadbeater#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  leadbeater-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - leadbeater
